#!/bin/sh
set -eu

if [ "$#" -gt 1 ]; then
  echo "Usage: $0 [path-to-repl]" >&2
  exit 2
fi

script_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
repo_root=$(CDPATH= cd -- "${script_dir}/.." && pwd)
repl_bin=${1:-"${repo_root}/build/ci-build/repl/repl"}

if [ ! -x "${repl_bin}" ]; then
  echo "repl binary not found or not executable: ${repl_bin}" >&2
  exit 2
fi

stderr_file=$(mktemp)
test_script=$(mktemp)
cleanup() {
  rm -f "${stderr_file}"
  rm -f "${test_script}"
}
trap cleanup EXIT INT TERM

# Build a script that keeps two locals alive, then pushes 255 nil literals.
# The next push crosses STACK_MAX before BUILD_VECTOR can collapse them.
{
  printf '# Generated by scripts/test_stack_limit.sh\n'
  printf 'fn explode() {\n'
  printf '  var keep1 = nil;\n'
  printf '  var keep2 = nil;\n'
  printf '  var v = ['
  i=1
  while [ "${i}" -le 255 ]; do
    if [ "${i}" -gt 1 ]; then
      printf ', '
    fi
    printf 'nil'
    i=$((i + 1))
  done
  printf '];\n'
  printf '  print(v);\n'
  printf '}\n\n'
  printf 'explode();\n'
} >"${test_script}"

if "${repl_bin}" -i "${test_script}" >/dev/null 2>"${stderr_file}"; then
  echo "FAIL stack_limit: expected runtime error, but the script succeeded" >&2
  exit 1
else
  status=$?
fi

if [ "${status}" -ne 70 ]; then
  echo "FAIL stack_limit: expected exit code 70, got ${status}" >&2
  cat "${stderr_file}" >&2
  exit 1
fi

if grep -F "PIPS Stack overflow." "${stderr_file}" >/dev/null; then
  echo "PASS stack_limit"
  exit 0
fi

echo "FAIL stack_limit: expected 'PIPS Stack overflow.' in stderr" >&2
cat "${stderr_file}" >&2
exit 1
