name: GCC Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CC: gcc
      CXX: g++
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build/ci-build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build/ci-build --parallel

      - name: Run example scripts
        run: sh ./scripts/run_examples.sh ./build/ci-build/repl/repl
